name: Release Lambda Zips

on:
  workflow_call:
    inputs:
      tag:
        description: "Semver Tag"
        required: true
        type: string
      Timestamp:
        description: "timestamp"
        required: true
        type: string

jobs:
  release-zips:
    runs-on: ubuntu-latest
    steps:
      - name: Set Timestamp
        id: timestamp
        run: echo "timestamp=$(date +"%Y%m%d%H%M%S")" >> "$GITHUB_OUTPUT"
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: ${{ github.ref != 'refs/heads/main' }}
          prerelease: ${{ github.ref != 'refs/heads/main' }}
          release_name: ${{ inputs.tag }}-${{ input.timestamp }}
          tag_name: ${{ inputs.tag }}-${{ input.timestamp }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Get Lambda artifact
        uses: actions/download-artifact@v4
        with:
          name: myFunction
          path: release

      - name: upload Lambda artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/myFunction.zip
          asset_name: myFunction-amd64.zip
          asset_content_type: application/zip

      - name: Get Lambda artifact sha256
        uses: actions/download-artifact@v4
        with:
          name: myFunction_sha256sum
          path: release

      - name: upload Lambda artifact sha256
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/myFunction.zip.sha256sum
          asset_name: myFunction-amd64.zip.sha256sum
          asset_content_type: application/zip

      - name: Get Lambda Layer artifact
        uses: actions/download-artifact@v4
        with:
          name: lambda_layer
          path: release

      - name: upload Lambda Layer artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/lambda_layer.zip
          asset_name: lambda_layer-amd64.zip
          asset_content_type: application/zip

      - name: Get Lambda Layer artifact sha256
        uses: actions/download-artifact@v4
        with:
          name: lambda_layer_sha256sum
          path: release

      - name: upload Lambda Layer artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/lambda_layer.zip.sha256sum
          asset_name: lambda_layer-amd64.zip.sha256sum
          asset_content_type: application/zip
